## Use an official Uvicorn-Gunicorn-FastAPI image
#FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9
#
## Set the working directory in the container
#COPY ./fastapi-app /app

#docker-compose up --build

# Dockerfile for FastAPI:
# Use an official Uvicorn-Gunicorn-FastAPI image
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Set the working directory in the container
WORKDIR /app

# Copy the FastAPI app code into the container at /app
COPY ./ /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port on which FastAPI will run
EXPOSE 80

# Command to run on container start
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

#docker-compose up --build
#docker-compose up --build test-runner
