version: '3'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    ports:
      - "8000:80"
    networks:
      - spring_boot_network

  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile_spring_boot
    ports:
      - "8080:8080"
    networks:
      - spring_boot_network

networks:
  spring_boot_network:
    external: true

#version: '3'
#
#services:
#  fastapi_app:
#    build:
#      context: .
#      dockerfile: Dockerfile_fastapi
#    ports:
#      - "8000:80"
#    networks:
#      - spring_boot_network
#
#networks:
#  spring_boot_network:
#    external: true
